version: '3'
services:
    bcb:
        image: "public.ecr.aws/d8b2x5c9/orange-stack-sat-bcb-pix"
        ports: 
            - 8082:8082
    itau:
        image: "public.ecr.aws/d8b2x5c9/orange-stack-sat-itau-erp"
        ports: 
            - 9091:9091
    postgres:
        image: 'postgres:alpine'
        ports:
            - 5432:5432
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: changeme
            POSTGRES_DB: postgres
            POSTGRES_HOST: postgres

    api-key-manager-grpc:
        image: witermendonca/keymanager-grpc
        ports:
            - 50051:50051
        depends_on:
            - postgres
            - bcb
            - itau
        environment:
            ITAU_URL: "http://itau:9091"
            BCB_URL: "http://bcb:8082"
            DB_URI: jdbc:postgresql://postgres/postgres
    api-key-manager-rest:
        image: witermendonca/keymanager-rest
        ports:
            - 8080:8080
        environment:
            KEY_MANAGER_HOST: api-key-manager-grpc

     